name: lynex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  chatwoot_sdk: ^0.0.9
  image_picker: ^1.2.1
  image: ^4.7.2
  path_provider: ^2.1.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/icon.png"
  android_12:
    image: "assets/icon/icon.png"
    color: "#FFFFFF"
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

dependency_overrides:
  photo_view: ^0.15.0
  flutter_linkify: ^6.0.0
  linkify: ^5.0.0